version: "3"
# docker-compose up --build
# docker-compose rm -v to delete everything and starting it up again.
services:

# HDFS
  namenode:
    build: ./hdfs/namenode
    image: hadoop-namenode:latest
    container_name: hadoop-namenode
    hostname: namenode
    networks:
      - hadoop-net
    ports:
      - "9870:9870"
    env_file:
      - common_env_config

  datanode:
    build: ./hdfs/datanode
    image: hadoop-datanode:latest
    container_name: hadoop-datanode
    hostname: datanode
    networks:
      - hadoop-net
    ports:
      - "9864:9864"
    env_file:
      - common_env_config
    environment:
      # wait-for-it
      - SERVICE_PRECONDITION=namenode:9870

# YARN
  resourcemanager:
    build: ./yarn/resourcemanager
    image: hadoop-resourcemanager:latest
    container_name: hadoop-resourcemanager
    hostname: resourcemanager
    networks:
      - hadoop-net
    ports:
      - "8088:8088"
    env_file:
      - common_env_config
    environment:
      # wait-for-it
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864

  nodemanager:
    build: ./yarn/nodemanager
    image: hadoop-nodemanager:latest
    container_name: hadoop-nodemanager
    hostname: nodemanager
    networks:
      - hadoop-net
    ports:
      - "8042:8042"
    env_file:
      - common_env_config
    environment:
      # wait-for-it
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088

  historyserver:
    build: ./yarn/historyserver
    image: hadoop-historyserver:latest
    container_name: hadoop-historyserver
    hostname: historyserver
    networks:
      - hadoop-net
    ports:
      - "8188:8188"
    env_file:
      - common_env_config
    environment:
      # wait-for-it
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088

networks:
  hadoop-net:
    driver: bridge